### ISSUE TITLE
请教下有没有马来西亚微软技术社区

### ISSUE THREAD

**Issue by tonyqus** [anonoz/mysgdev#14]
如题

**Comment by anonoz** [comment]
我觉得你可以从 developer kaki 面子书社群问起，那边的管理员好像跟微软有关
________________________________
From: Tony Qu ***@***.***>
Sent: Tuesday, October 15, 2024 11:19:13 AM
To: anonoz/mysgdev ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [anonoz/mysgdev] 请教下有没有马来西亚微软技术社区 (Issue #14)


如题

―

**Comment by tonyqus** [comment]
好，我试试，谢谢
